-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2015-11-23 23:41:32 EST



declare global temporary table SESSION.trns
(   /*  TRNS_ID		INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, */
    TRNS_TYPE	CHAR NOT NULL ,							/* type is 'I' income or 'E' expense */
    TRNS_DT		DATE NOT NULL,							/*  transaction date */
    AMOUNT		DECIMAL (12,2) NOT NULL,		/*  dollar amount */
		WITHWHOM	VARCHAR (64) NOT NULL,			/* with whom the transaction was made */
    DESCRIP		VARCHAR (255) default null,	/* description */
		PAIDWITH	VARCHAR(24),								/* how paid eq "CASH", "BofA VISA", "CHECK", */
		UPDT			DATE NOT NULL with default current_date,	/* date this row was created or updated */
		KEYWORD1	VARCHAR(16) default null,		/* category */
		KEYWORD2	VARCHAR(16) default null,
		KEYWORD3	VARCHAR(16)	default null,
    ADDRESS		VARCHAR (128) default null
) ON COMMIT PRESERVE ROWS not logged;

--  My account to which the  the tranaction  was applied - need not be detailed
--  like "cash" but detail is okay in the description
CREATE TABLE ACCOUNT
  (
    --  Account id
    ACCOUNT CHAR (8) NOT NULL ,
    --  Description and/or details
    DESCRIP VARCHAR (128) NOT NULL
  ) ;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY ( ACCOUNT ) ;


--  A list of possible tranaction categories.
CREATE TABLE CAT
  (
    --  Category
    CAT CHAR (8) NOT NULL ,
    --  Description of the category
    DESCRIP VARCHAR (128) NOT NULL
  ) ;
ALTER TABLE CAT ADD CONSTRAINT CAT_PK PRIMARY KEY ( CAT ) ;

-- drop SEQUENCE TRNSID RESTRICT;
-- CREATE SEQUENCE TRNSID;

--  Transaction is  either income or expense
--ALTER TABLE TRNS_CAT DROP CONSTRAINT TRNS_CAT_TRANSACT_FK
--ALTER TABLE TRANSACT DROP CONSTRAINT TRANSACT_PK;
DROP TABLE TRANSACT;
CREATE TABLE TRANSACT
  (
    TRNS_ID		INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TRNS_TYPE	CHAR NOT NULL ,							/* type is 'I' income or 'E' expense */
    TRNS_DT		DATE NOT NULL,							/*  transaction date */
    AMOUNT		DECIMAL (12,2) NOT NULL,		/*  dollar amount */
		WITHWHOM	VARCHAR (64) NOT NULL,			/* with whom the transaction was made */
    DESCRIP		VARCHAR (255) default null,	/* description */
		PAIDWITH	VARCHAR(24),								/* how paid eq "CASH", "BofA VISA", "CHECK", */
		UPDT			DATE NOT NULL with default current_date,	/* date this row was created or updated */
		KEYWORD1	VARCHAR(16) default null,		/* category */
		KEYWORD2	VARCHAR(16) default null,
		KEYWORD3	VARCHAR(16)	default null,
    ADDRESS		VARCHAR (128) default null	/*  where the transaction happened */
	);
--ALTER TABLE TRANSACT ADD CONSTRAINT TRANSACT_PK PRIMARY KEY ( TRNS_ID ) ;



--  Transaction category allows for multiple categories per transactio
CREATE TABLE TRNS_CAT
  (
    --  Possible place to leave some information
    NOTE VARCHAR (128) ,
    --  Primary id
    TRNS_ID INTEGER NOT NULL ,
    --  Category
    CAT CHAR (8) NOT NULL
  ) ;
ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_PK PRIMARY KEY ( TRNS_ID, CAT ) ;


ALTER TABLE TRANSACT ADD CONSTRAINT TRANSACT_ACCOUNT_FK FOREIGN KEY ( ACCOUNT ) REFERENCES ACCOUNT ( ACCOUNT ) ;

ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_CAT_FK FOREIGN KEY ( CAT ) REFERENCES CAT ( CAT ) ;

--ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_TRANSACT_FK FOREIGN KEY ( TRNS_ID ) REFERENCES TRANSACT ( TRNS_ID ) ;

