-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2015-11-23 23:41:32 EST


--  My account to which the  the tranaction  was applied - need not be detailed
--  like "cash" but detail is okay in the description
CREATE TABLE ACCOUNT
  (
    --  Account id
    ACCOUNT CHAR (8) NOT NULL ,
    --  Description and/or details
    DESCRIP VARCHAR (128) NOT NULL
  ) ;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY ( ACCOUNT ) ;


--  A list of possible tranaction categories.
CREATE TABLE CAT
  (
    --  Category
    CAT CHAR (8) NOT NULL ,
    --  Description of the category
    DESCRIP VARCHAR (128) NOT NULL
  ) ;
ALTER TABLE CAT ADD CONSTRAINT CAT_PK PRIMARY KEY ( CAT ) ;


--  Transaction is  either income or expense
CREATE TABLE TRANSACT
  (
    --  Primary id
    TRNS_ID INTEGER NOT NULL ,
    --  Transaction type is income or expense
    TRNS_TYPE INTEGER NOT NULL ,
    --  Transaction date
    TRNS_DT DATE NOT NULL ,
    --  Dollar amount of transaction.
    AMOUNT DECIMAL (12,2) NOT NULL ,
    --  Transaction Description
    DESCRIP VARCHAR (255) NOT NULL ,
    --  Where the tranaction happened
    LOC VARCHAR (128) ,
    --  Account id
    ACCOUNT CHAR (8) NOT NULL
  ) ;
ALTER TABLE TRANSACT ADD CONSTRAINT TRANSACT_PK PRIMARY KEY ( TRNS_ID ) ;


--  Transaction category allows for multiple categories per transactio
CREATE TABLE TRNS_CAT
  (
    --  Possible place to leave some information
    NOTE VARCHAR (128) ,
    --  Primary id
    TRNS_ID INTEGER NOT NULL ,
    --  Category
    CAT CHAR (8) NOT NULL
  ) ;
ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_PK PRIMARY KEY ( TRNS_ID, CAT ) ;


ALTER TABLE TRANSACT ADD CONSTRAINT TRANSACT_ACCOUNT_FK FOREIGN KEY ( ACCOUNT ) REFERENCES ACCOUNT ( ACCOUNT ) ;

ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_CAT_FK FOREIGN KEY ( CAT ) REFERENCES CAT ( CAT ) ;

ALTER TABLE TRNS_CAT ADD CONSTRAINT TRNS_CAT_TRANSACT_FK FOREIGN KEY ( TRNS_ID ) REFERENCES TRANSACT ( TRNS_ID ) ;

