-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2015-11-22 23:00:52 EST





CREATE TABLE label
  (
    label   CHAR (12) NOT NULL ,
    descrip VARCHAR2 (255) NOT NULL
  ) ;
ALTER TABLE label ADD CONSTRAINT label_PK PRIMARY KEY ( label ) ;


drop table trans_label;
CREATE TABLE trans_label
  (
    label_label CHAR (12) NOT NULL ,
    transact_id INTEGER NOT NULL
  ) ;
ALTER TABLE trans_label ADD CONSTRAINT trans_label_PK PRIMARY KEY ( label_label, transact_id ) ;


drop table transact;
CREATE TABLE transact
  (
    id         INTEGER NOT NULL ,
    trans_dt   DATE NOT NULL ,
    price      DECIMAL (10,2) ,
    type       INTEGER NOT NULL ,
    Descrip    VARCHAR (255) NOT NULL ,
    location   VARCHAR (128) ,
    withwhom   VARCHAR (64) NOT NULL
  ) ;
ALTER TABLE transact ADD CONSTRAINT transact_PK PRIMARY KEY ( id ) ;


ALTER TABLE trans_label ADD CONSTRAINT trans_label_label_FK FOREIGN KEY ( label_label ) REFERENCES label ( label ) ;

ALTER TABLE trans_label ADD CONSTRAINT trans_label_transact_FK FOREIGN KEY ( transact_id ) REFERENCES transact ( id ) ;

